Feat/2-auth
CPR2U/CPR2U-Server pull request #6
Opened 2023-03-08 11:16 UTC by yejin9858

## 📌 관련 이슈
#2 

## ✨ 작업 내용

- API 작성
  - /auth/login : 로그인
  - /auth/signup : 회원가입
  - /auth/verification : 코드 발급 (코드 메세지 보내기는 나중에 추가 예정)
  - /auth/auto-login : 자동 로그인, 토큰 재발급
  
- 테스트 코드 작성
- Feat/1-education 브랜치랑 합치면서 생긴 conflict, 현재 브랜치에서 변경된 사항으로 인해 생긴 error 수정

## 📚 레퍼런스 (또는 새로 알게 된 내용) 혹은 궁금한 사항들

- swagger... 진짜 하고싶은데 우선 사항이 아닌 것 같아서 나중에 시간 날 때 하겠습니다...
- 프론트한테는 swagger 문서 참고해서 확인 + postman 테스트 방식으로 하라고 하면 될 듯 합니다. - access_token은 헤더 Authorization으로 넣으면 됩니다. Bearer도 해보고 싶었지만? 일단 우선순위가 아닌 것 같아 나중에 시간 날 때 하겠습니다.

2023-03-08 16:23 UTC, raae7742 requested changes
와,, API 단위 테스트 코드까지 짜셨군요 😭😭 너무 완전 고생 많으셨습니다..
ResponseCode 코드 양식만 내일 같이 정하면 머지해도 좋을 것 같아요!
코드 리뷰 덕분에 새로운 지식 많이 얻고 갑니다! 푹 쉬세용 😊s2

2023-03-08 16:23 UTC, raae7742 commented on src/main/java/com/mentionall/cpr2u/user/domain/User.java
> +    private String deviceToken;
device 토큰도 테이블을 분리하는게 좋지 않을까요?
토큰들은 나중에 MySQL이 아닌 다른 DB에 저장해두는게 좋을 것 같아서요!

2023-03-08 16:23 UTC, raae7742 commented on src/main/java/com/mentionall/cpr2u/user/domain/User.java
> +    @ElementCollection(fetch = FetchType.EAGER)
컬렉션 리스트에는 `@OneToMany` 대신 `@ElementCollection` 이라는 어노테이션이 따로 있었군요..! 새롭게 알아갑니당
나중에 N+1 문제를 방지하기 위해 FetchType.LAZY로 설정하는건 어떨까요?

2023-03-08 16:23 UTC, raae7742 commented on src/main/java/com/mentionall/cpr2u/user/service/UserService.java
> +        else throw new CustomException(ResponseCode.NOT_FOUND_USER_EXCEPTION);
`else`가 없어도 좋을 것 같아요!

2023-03-08 16:23 UTC, raae7742 commented on src/main/java/com/mentionall/cpr2u/util/exception/ResponseCode.java
> +    LECTURE_NOT_FOUND(HttpStatus.INTERNAL_SERVER_ERROR, "해당 강의를 찾을 수 없습니다."),
우리 ResponseCode에서 통일된 코드 양식이 있으면 좋을 것 같아요 😉 내일 같이 얘기해봐요!

2023-03-08 16:23 UTC, raae7742 commented on src/main/java/com/mentionall/cpr2u/user/service/UserService.java
> +        if(refreshToken != null)
null 확인 코드를 없애면 가독성이 더 좋아질 것 같은데 해결방법이 없을까요 ?.?

2023-03-08 23:25 UTC, yejin9858 commented
> 와,, API 단위 테스트 코드까지 짜셨군요 😭😭 너무 완전 고생 많으셨습니다..
> 
> ResponseCode 코드 양식만 내일 같이 정하면 머지해도 좋을 것 같아요!
> 
> 코드 리뷰 덕분에 새로운 지식 많이 얻고 갑니다! 푹 쉬세용 😊s2

우왓 이것이 코드리뷰군요... 제가 지금까지 한 건 가짜였어요...! 꼼꼼한 리뷰 감사합니다☺️ 현애님이 지적한 부분 다 동의합니다. 오후에 고쳐놓을게요!!

2023-03-09 09:29 UTC, raae7742 approved these changes

2023-03-09 09:29 UTC, merged